In [33]:
import numpy as np
import pandas as pd

In [34]:
data=pd.read_csv("result.csv")
data

   a/b  fs/threshold  numInp  cnum   bias  svrc  svrp  trnq2  chkq2
0    a          0.80    87.0   2.0  2.791   2.1  0.05  0.529  0.436
1    a          0.80    87.0   2.0  2.740   2.2  0.05  0.529  0.439
2    b          0.80    87.0   2.0  2.699   2.3  0.05  0.529  0.437
3    b          0.80    87.0   2.0  2.660   2.4  0.05  0.530  0.435
4    a          0.85   284.0   2.0  3.448   2.1  0.05  0.691  0.483
5    b          0.85   284.0   2.0  3.469   2.2  0.05  0.694  0.483
6    b          0.85   284.0   2.0  3.491   2.3  0.05  0.696  0.482
7    b          0.85   284.0   2.0  3.513   2.4  0.05  0.699  0.481
8    a          0.90   860.0   2.0  2.382   2.1  0.05  0.814  0.565
9    b          0.90   860.0   2.0  2.380   2.2  0.05  0.815  0.565
10   b          0.90   860.0   2.0  2.378   2.3  0.05  0.817  0.565
11   b          0.90   860.0   2.0  2.376   2.4  0.05  0.818  0.564

In [35]:
np.max(data['chkq2'])

0.56499999999999995